=== helmuthelmut2000/Blinker/Packages/Beckhoff.TwinCAT.HMI.PostgresHistorize.22.0.7198/runtimes/linux-arm64/native/TcHmiPostgresHistorize.Schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "pointInTime": {
      "configDescription": "descPointInTime",
      "oneOf": [
        {
          "type": "string",
          "format": "timespan",
          "configDescription": "descPointInTimeTimespan"
        },
        {
          "type": "string",
          "format": "date-time",
          "configDescription": "descPointInTimeTimestamp"
        },
        {
          "type": "string",
          "enum": [ "Null", "First", "Latest" ],
          "configDescription": "descPointInTimeKeywords"
        }
      ]
    }
  },
  "properties": {
    "databaseSettings": {
      "category": "database",
      "configDescription": "descDatabaseSettings",
      "defaultConfigurable": true,
      "type": "object",
      "properties": {
        "connectionString": {
          "type": "string",
          "format": "multiline",
          "default": "Server=localhost; Port=5432; Database=historize_postgres; Uid=postgres; Pwd=@{password};Timeout=10;",
          "configDescription": "descConnectionString"
        },
        "password": {
          "type": "string",
          "format": "masked",
          "propertyOrder": 5
        },
        "tableId": {
          "configDescription": "descTableId",
          "type": "number",
          "default": 1,
          "propertyOrder": 7
        }

      },
      "required": [ "connectionString", "tableId", "password" ]
    },
    "historizedSymbolList": {
      "configDescription": "descHistorizedSymbolList",
      "defaultConfigurable": true,
      "type": "object",
      "propertyOrder": 1,
      "additionalProperties": {
        "configDescription": "descHistorizedSymbol",
        "title": "historizeSymbol",
        "keyOptionMethod": {
          "symbol": "ListSymbolNames"
        },
        "type": "object",
        "properties": {
          "version": {
            "type": "number",
            "optionMethodAllowCustom": false,
            "optionMethod": {
              "symbol": "GetSchema::{key}",
              "version": 2.0,
              "writeValue": {
                "symbol": {
                  "$data": "#/properties/historizedSymbolList/additionalProperties"
                },
                "resolve": "AllVersions"
              },
              "orderBy": "DESC"
            },
            "default": 1.0
          },
          "maxEntries": {
            "type": "integer",
            "default": 10000
          },
          "interval": {
            "type": "string",
            "format": "timespan",
            "default": "PT1S",
            "formatMinimum": "PT0.01S"
          },
          "recordingEnabled": {
            "type": "boolean",
            "default": true
          },
          "deletionInterval": {
            "configDescription": "descDeletionInterval",
            "type": "string",
            "format": "timespan",
            "default": "PT1M",
            "formatMinimum": "PT1S"
          }
        },
        "required": [ "maxEntries", "interval", "recordingEnabled", "deletionInterval" ],
        "additionalProperties": false
      }
    },
    "enableCompression": {
      "configDescription": "descCompression",
      "propertyOrder": 2,
      "type": "boolean",
      "default": false
    },
    "compressAfter": {
      "configDescription": "descCompressAfter",
      "propertyOrder": 3,
      "type": "string",
      "format": "timespan",
      "formatMinimum": "PT30M",
      "default": "P30D"
    },
    "compressionScheduleInterval": {
      "configDescription": "descCompressionScheduleInterval",
      "propertyOrder": 4,
      "type": "string",
      "format": "timespan",
      "formatMinimum": "PT30M",
      "default": "P30D"
    }
  },
  "required": [
    "databaseSettings",
    "historizedSymbolList"
  ],
  "type": "object",
  "additionalProperties": false
}

=== helmuthelmut2000/Blinker/HMI_Blinker/Server/TcHmiPostgresHistorize/TcHmiPostgresHistorize.Config.default.json
{
    "compressAfter": "P30D",
    "compressionScheduleInterval": "P30D",
    "databaseSettings": {
        "connectionString": "Server=localhost; Port=5432; Database=historize_postgres; Uid=postgres; Pwd=@{password};Timeout=10;",
        "password": "AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA8jLODi7tXk6PljZaIEyczwAAAAAeAAAARQBuAGMAcgB5AHAAdABlAGQAIABkAGEAdABhAAAAEGYAAAABAAAgAAAAmiI3q1/Ro+4Xxu7yQMbLa+0v7b1xk4bM8qlRmgP2B/oAAAAADoAAAAACAAAgAAAAR9MLLUgyjGF1nImSPvdhakhnH2CW8ypLKLP9x0/hhqoQAAAAVmrQEB65m9gxVsqd1O7630AAAAD+QYOt9aliZtvZP1hHwbU84Z1ew1Kc36pAwfwxnX+o8GV254X1eLOE898yIVo5X0f2Ak5hMaUrln61TBoAn3oO",
        "tableId": 1.0
    },
    "enableCompression": false,
    "historizedSymbolList": {
        "ADS.PLC1.GVL_Blinker.bBlink": {
            "deletionInterval": "PT1M",
            "interval": "PT1S",
            "maxEntries": 10000,
            "recordingEnabled": true
        },
        "ADS.PLC1.GVL_Blinker.rStatus": {
            "deletionInterval": "PT1M",
            "interval": "PT1S",
            "maxEntries": 10000,
            "recordingEnabled": true,
            "version": 1.0
        }
    }
}
